In [1]:
import numpy as np #ref
import os
from os import path as op
import string
import re
from subprocess import Popen
import xarray as xr #ref
import metpy #ref
import matplotlib.pyplot as plt #ref
import cartopy.crs as ccrs #ref
import cartopy.feature as cfeature
from pyresample import image, geometry #ref
import seaborn as sns #ref
import netCDF4
sns.set(style="darkgrid")
%matplotlib inline

#sys.path.append('')

/opt/home/adomakor412/.conda/envs/NOAA/lib/python3.7/site-packages/xarray/core/merge.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)


In [3]:
file = '../../goesdata/DQF/221/OR_ABI-L1b-RadF-M6C07_G16_s20192210000548_e20192210010268_c20192210010328.npy'
myFile = np.load(file)

In [4]:
print(myFile)

[[0.7789913  0.7680408  0.7226746  ... 0.50835854 0.56780386 0.62881356]
 [0.7789913  0.7226746  0.70233804 ... 0.53808117 0.5990909  0.6460214 ]
 [0.7508329  0.70233804 0.70233804 ... 0.5803187  0.64445704 0.65540755]
 ...
 [0.07503328 0.06564717 0.06564717 ... 0.8665949  0.8634662  0.8587732 ]
 [0.07816197 0.06095411 0.06564717 ... 0.8055852  0.7742982  0.79776347]
 [0.07816197 0.06877588 0.06095411 ... 0.68982327 0.70546675 0.7508329 ]]
