In [2]:
import pandas as pd
import numpy as np #ref
import os
from os import path as op
import string
import re
from subprocess import Popen
import xarray as xr #ref
import metpy #ref
import matplotlib.pyplot as plt #ref
import cartopy.crs as ccrs #ref
import cartopy.feature as cfeature
from pyresample import image, geometry #ref
import seaborn as sns #ref
import netCDF4
sns.set(style="darkgrid")
%matplotlib inline

#sys.path.append('')

/opt/home/adomakor412/.conda/envs/NOAA/lib/python3.7/site-packages/xarray/core/merge.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)


In [6]:
file = '../../goesdata/DQF/221/OR_ABI-L1b-RadF-M6C07_G16_s20192210000548_e20192210010268_c20192210010328.npy'
myFile = np.load(file)

In [7]:
print(myFile)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [1]:
G16 = '../../goesdata/sample/OR_ABI-L1b-RadF-M6C07_G16_s20192210000'
G17 = '../../goesdata/sample/OR_ABI-L1b-RadF-M6C07_G17_s20192210000'

In [4]:
d16 = pd.DataFrame(np.load(G16))
d17 = pd.DataFrame(np.load(G17))

In [5]:
d16

0         1         2         3         4         5         6    \
0     0.778991  0.768041  0.722675  0.717982  0.671051  0.583447  0.580319   
1     0.778991  0.722675  0.702338  0.717982  0.635071  0.580319  0.580319   
2     0.750833  0.702338  0.702338  0.685130  0.600655  0.600655  0.575626   
3     0.755526  0.755526  0.694516  0.633507  0.575626  0.575626  0.570933   
4     0.761783  0.761783  0.708595  0.616299  0.616299  0.564675  0.574061   
...        ...       ...       ...       ...       ...       ...       ...   
996   0.082855  0.082855  0.096934  0.104756  0.104756  0.101627  0.095370   
997   0.068776  0.068776  0.084419  0.103192  0.103192  0.103192  0.096934   
998   0.075033  0.065647  0.065647  0.092241  0.103192  0.103192  0.098499   
999   0.078162  0.060954  0.065647  0.078162  0.101627  0.109449  0.109449   
1000  0.078162  0.068776  0.060954  0.078162  0.100063  0.115706  0.109449   

           7         8         9    ...       391       392       393  \
0     0.575626  0.614734  0.682001  ...  0.553725  0.534953  0.534953   
1     0.583447  0.630378  0.630378  ...  0.627249  0.555289  0.555289   
2     0.595962  0.630378  0.630378  ...  0.689823  0.689823  0.606913   
3     0.594398  0.594398  0.614734  ...  0.708595  0.708595  0.647586   
4     0.592833  0.592833  0.622556  ...  0.703902  0.680437  0.583447   
...        ...       ...       ...  ...       ...       ...       ...   
996   0.090677  0.090677  0.085984  ...  0.766476  0.696081  0.722675   
997   0.093805  0.093805  0.090677  ...  0.733625  0.733625  0.722675   
998   0.095370  0.090677  0.090677  ...  0.716417  0.716417  0.667922   
999   0.103192  0.096934  0.096934  ...  0.675744  0.600655  0.600655   
1000  0.112578  0.104756  0.096934  ...  0.682001  0.636635  0.636635   

           394       395       396       397       398       399       400  
0     0.511487  0.495844  0.494279  0.508359  0.508359  0.567804  0.628814  
1     0.527131  0.498972  0.503665  0.538081  0.538081  0.599091  0.646021  
2     0.544339  0.522438  0.531824  0.580319  0.580319  0.644457  0.655408  
3     0.544339  0.556853  0.617863  0.617863  0.663229  0.686695  0.633507  
4     0.505230  0.514616  0.583447  0.583447  0.663229  0.650714  0.552160  
...        ...       ...       ...       ...       ...       ...       ...  
996   0.744576  0.788377  0.805585  0.805585  0.830615  0.872852  0.838437  
997   0.749269  0.804021  0.844694  0.844694  0.865031  0.880674  0.868159  
998   0.728932  0.804021  0.850951  0.866595  0.866595  0.863466  0.858773  
999   0.671051  0.768041  0.819664  0.805585  0.805585  0.774298  0.797763  
1000  0.725803  0.775863  0.752397  0.689823  0.689823  0.705467  0.750833  

[1001 rows x 401 columns]

In [6]:
d17

0         1         2         3         4         5         6    \
0     0.711724  0.663229  0.636635  0.636635  0.597527  0.545903  0.520873   
1     0.675744  0.625685  0.639764  0.639764  0.605348  0.542774  0.520873   
2     0.664794  0.613170  0.620992  0.620992  0.578754  0.525566  0.517745   
3     0.686695  0.635071  0.597527  0.549032  0.549032  0.508359  0.511487   
4     0.688259  0.658536  0.606913  0.542774  0.542774  0.508359  0.513052   
...        ...       ...       ...       ...       ...       ...       ...   
996   0.037489  0.032796  0.031231  0.031231  0.031231  0.031231  0.037489   
997   0.034360  0.031231  0.029667  0.031231  0.031231  0.028103  0.034360   
998   0.031231  0.028103  0.029667  0.029667  0.034360  0.026538  0.028103   
999   0.029667  0.029667  0.029667  0.029667  0.029667  0.029667  0.028103   
1000  0.029667  0.028103  0.028103  0.028103  0.028103  0.028103  0.026538   

           7         8         9    ...       391       392       393  \
0     0.530259  0.530259  0.564675  ...  0.553725  0.516180  0.484893   
1     0.525566  0.525566  0.563111  ...  0.589705  0.589705  0.509923   
2     0.536517  0.561546  0.561546  ...  0.664794  0.664794  0.572497   
3     0.533388  0.549032  0.549032  ...  0.689823  0.635071  0.635071   
4     0.530259  0.547467  0.586576  ...  0.669487  0.595962  0.595962   
...        ...       ...       ...  ...       ...       ...       ...   
996   0.040618  0.046875  0.051568  ...  0.664794  0.658536  0.658536   
997   0.034360  0.037489  0.037489  ...  0.694516  0.667922  0.667922   
998   0.029667  0.032796  0.032796  ...  0.664794  0.664794  0.617863   
999   0.028103  0.028103  0.028103  ...  0.583447  0.583447  0.545903   
1000  0.026538  0.026538  0.026538  ...  0.608477  0.536517  0.555289   

           394       395       396       397       398       399       400  
0     0.483329  0.469250  0.462992  0.483329  0.534953  0.511487  0.588140  
1     0.483329  0.483329  0.470814  0.483329  0.555289  0.534953  0.588140  
2     0.502101  0.484893  0.484893  0.502101  0.555289  0.555289  0.595962  
3     0.522438  0.519309  0.519309  0.569368  0.620992  0.635071  0.635071  
4     0.494279  0.491151  0.553725  0.553725  0.633507  0.617863  0.617863  
...        ...       ...       ...       ...       ...       ...       ...  
996   0.711724  0.766476  0.789942  0.789942  0.791506  0.791506  0.791506  
997   0.722675  0.772734  0.772734  0.799328  0.797763  0.786813  0.786813  
998   0.708595  0.774298  0.774298  0.796199  0.753962  0.753962  0.721110  
999   0.658536  0.658536  0.755526  0.758655  0.753962  0.696081  0.653843  
1000  0.658536  0.638200  0.675744  0.758655  0.696081  0.611606  0.653843  

[1001 rows x 401 columns]